### ISSUE TITLE
User profile stream could not be initialized

### ISSUE THREAD

**Issue by st5000** [humhub/humhub#3976]
HumHub version 1.5.0-beta.1

![Screenshot_2020-04-07](https://user-images.githubusercontent.com/57590912/78710883-617c5100-7916-11ea-8034-46f499d6faa4.png)

```
[error][yii\base\UnknownMethodException] yii\base\UnknownMethodException: Calling unknown method: humhub\modules\user\components\ProfileStream::leftJoin() in /opt/humhub/protected/vendor/yiisoft/yii2/base/Component.php:300
Stack trace:
#0 /opt/humhub/protected/humhub/modules/user/components/ProfileStream.php(63): yii\base\Component->__call('leftJoin', Array)
#1 /opt/humhub/protected/humhub/modules/stream/actions/ContentContainerStream.php(38): humhub\modules\user\components\ProfileStream->handleContentContainer()
#2 /opt/humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php(109): humhub\modules\stream\actions\ContentContainerStream->init()
#3 /opt/humhub/protected/vendor/yiisoft/yii2/base/Action.php(62): yii\base\BaseObject->__construct(Array)
#4 [internal function]: yii\base\Action->__construct('stream', Object(humhub\modules\user\controllers\ProfileController), Array)
#5 /opt/humhub/protected/vendor/yiisoft/yii2/di/Container.php(400): ReflectionClass->newInstanceArgs(Array)
#6 /opt/humhub/protected/vendor/yiisoft/yii2/di/Container.php(159): yii\di\Container->build('humhub\\modules\\...', Array, Array)
#7 /opt/humhub/protected/vendor/yiisoft/yii2/BaseYii.php(365): yii\di\Container->get('humhub\\modules\\...', Array, Array)
#8 /opt/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(227): yii\BaseYii::createObject(Array, Array)
#9 /opt/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(126): yii\base\Controller->createAction('stream')
#10 /opt/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('stream', Array)
#11 /opt/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('user/profile/st...', Array)
#12 /opt/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request))
#13 /opt/humhub/index.php(25): yii\base\Application->run()
#14 {main}
```

**Comment by Smilefounder** [comment]
Go the same issue.

**Comment by peksel** [comment]
got the same too

**Comment by ArchBlood** [comment]
Could you provide more information? PHP version? PHP extension versions? How to reproduce this? I'm not seeing any problems with v1.5.0-beta.1 like this. :frowning_face:

**Comment by st5000** [comment]
PHP 7.3.15. You should enable friendship module to reproduce this.

**Comment by st5000** [comment]
Definitely here:
./protected/humhub/modules/user/components/ProfileStream.php line 63:
```
            if (Yii::$app->getModule('friendship')->getIsEnabled()) {
                $this->leftJoin('user_friendship cff', 'cuser.id=cff.user_id AND cff.friend_user_id=:fuid', [':fuid' => $this->user->id]);
                $conditionUser .= ' OR (content.visibility = 0 AND cff.id IS NOT NULL)';  // users are friends
            }
```

**Comment by ArchBlood** [comment]
Change to this and see if it works after.
```php
            if (Yii::$app->getModule('friendship')->getIsEnabled()) {
                $query = User::find();
                $query->leftJoin('user_friendship cff', 'cuser.id=cff.user_id AND cff.friend_user_id=:fuid', [':fuid' => $this->user->id]);
                $conditionUser .= ' OR (content.visibility = 0 AND cff.id IS NOT NULL)';  // users are friends
                return $query;
            }
```

**Comment by st5000** [comment]
No error anymore BUT user profile stream now shows posts of him on spaces too.

**Comment by ArchBlood** [comment]
> No error anymore BUT user profile stream now shows posts of him on spaces too.

Not seeing this on my end, will do some more checks @st5000

**Comment by ArchBlood** [comment]
Only issue I'm seeing right now is when I post to someone else's profile then unfriend them and refriend them the post shows on my profile but not the other person's anymore, other than that I'm not sure how to reproduce your side. :thinking:

**Comment by st5000** [comment]
On Sara profile stream, you see Sara's "Testing" post on Welcome Space.

With HH 1.4, user posts on space are not displayed on user profile stream. Unless this behavior has changed since HH 1.5 ?

**Comment by ArchBlood** [comment]
In v1.5 space posts were integrated into profile streams.

**Comment by st5000** [comment]
OK then your patch works. Thanks :1st_place_medal:

**Comment by ArchBlood** [comment]
Glad that it worked, although I'll wait for the HumHub staff to work their magic as I'm sure there is a better solution to the issue than my little patch. :smile:

**Comment by st5000** [comment]
It seems that there is still a bug related to permissions since not friend can see all private posts to space on any user profile stream.

**Comment by ArchBlood** [comment]
@st5000 would seem there is a permissions issue when it comes to private space posts being viewable on profiles this also happens when you're not a friend or a follower.

![Screenshot_1](https://user-images.githubusercontent.com/35392110/78835842-e91d9a80-79be-11ea-9e78-8085cb40b81f.png)
![Screenshot_2](https://user-images.githubusercontent.com/35392110/78835847-eb7ff480-79be-11ea-80c4-9cbc1aa5e2d8.png)
![Screenshot_3](https://user-images.githubusercontent.com/35392110/78836080-53ced600-79bf-11ea-8ada-b0bf855b64e3.png)

**Comment by lgoehrs** [comment]
Very easy fix

in the file
/opt/humhub/protected/humhub/modules/user/components/ProfileStream.php

if isdoiing a 
$this->leftJoin

instead of a 

$this->activeQuery->leftJoin


if (Yii::$app->getModule('friendship')->getIsEnabled()) {
                $this->activeQuery->leftJoin('user_friendship cff', 'cuser.id=cff.user_id AND cff.friend_user_id=:fuid', [':fuid' => $this->user->id]);
                $conditionUser .= ' OR (content.visibility = 0 AND cff.id IS NOT NULL)';  // users are friends

I will let somelse commit the fix

**Comment by Smilefounder** [comment]
> Change to this and see if it works after.
> 
> ```
>             if (Yii::$app->getModule('friendship')->getIsEnabled()) {
>                 $query = User::find();
>                 $query->leftJoin('user_friendship cff', 'cuser.id=cff.user_id AND cff.friend_user_id=:fuid', [':fuid' => $this->user->id]);
>                 $conditionUser .= ' OR (content.visibility = 0 AND cff.id IS NOT NULL)';  // users are friends
>                 return $query;
>             }
> ```

This fixed from my side.

**Comment by lgoehrs** [comment]
I fixed it this way

if (Yii::$app->getModule('friendship')->getIsEnabled()) {
                $this->activeQuery->leftJoin('user_friendship cff', 'cuser.id=cff.user_id AND cff.friend_user_id=:fuid', [':fuid' => $this->user->id]);
                $conditionUser .= ' OR (content.visibility = 0 AND cff.id IS NOT NULL)';  // users are friends
            }



Leo Goehrs
LPG HOLDING COPORATION
48, rue Lehot
92600 Asnières-sur-Seine
mobile +33 6 89 99 14 06
mail mailto:leo@lpghc.com

**Comment by luke-** [comment]
Thanks for your help!

**Comment by st5000** [comment]
@luke- This fix don't work as the same as from @ArchBlood. Please check and compare with pinned posts on spaces.

**Comment by st5000** [comment]
Forget my previous post, it's related to feature #3950 that annoying.

**Comment by buddh4** [comment]
Do you have problems with the feature or do you just prefer the old behavior? You can change the profile behavior by configuration.

**Comment by st5000** [comment]
Both...

Old pinned posts from all spaces (including old and archived ones) are now displayed on top of user profile stream.

It would be nice to have the ability to disable this feature or at least, pinned posts on spaces must be excluded from user profile stream.

**Comment by luke-** [comment]
The bug with the pinned posts is now fixed.

**Comment by buddh4** [comment]
Perhaps we should add an "Only profile posts" stream filter on the profile. And depending on the configuration activate or deactivate this filter by default. I think generally the inclusion of all user posts in the profile is a very useful feature especially in communities in which the profile is otherwise hardly used.

**Comment by luke-** [comment]
@buddh4 good idea with the filter option!

**Comment by luke-** [comment]
Should we create a new issue (enhancement) with such filter option?
Maybe we can integrate this with 1.6

**Comment by ArchBlood** [comment]
This fix does not fix the issue when friends post on your stream, it's only visible when on your own profile.

### After modifying with fixes
![Screenshot_1](https://user-images.githubusercontent.com/35392110/79077099-d52ead00-7ccc-11ea-9538-4d3e530a1885.png)
![Screenshot_2](https://user-images.githubusercontent.com/35392110/79077100-d7910700-7ccc-11ea-9a6f-d7931cae68a7.png)

And even my fix doesn't work for this, probably something to do with the container that allows others to post on your profile that has to be fixed.

**Comment by luke-** [comment]
@ArchBlood Which notification do you mean?

**Comment by ArchBlood** [comment]
When `$user1` posts on `$user2`'s profile `$user1` gets a notification saying that there was a post made, the notification should take you there but the container for that notification when you load the page shows the above screenshot, nothing but a blank container and the container that the post from `$user2` on `$user1`'s profile simply disappears on page reload and only shows on `$user2`'s profile.

**Comment by luke-** [comment]
@ArchBlood The last commit should fixes the issue, can you confirm that?

**Comment by ArchBlood** [comment]
@luke- that fixed it :+1:

**Comment by luke-** [comment]
Issue regarding the Filter idea:
https://github.com/humhub/humhub/issues/3995
