### ISSUE TITLE
Some emoji cann't be displayed on notification.

### ISSUE THREAD

**Issue by tomofu74** [humhub/humhub#4115]
### What steps will reproduce the problem?
Some emoji , like :world_map:, :triangular_flag_on_post: are not displayed on Notification. But they are displayed on stream post content correctly.
<img width="242" alt="2020-05-17 193929" src="https://user-images.githubusercontent.com/19162094/82142291-2e62a100-9876-11ea-83be-c18ec12754a5.png">

### What is the expected result?
If they were displayed on stream post, they should be displayed on notification as same, just like that.

### What do you get instead?
( see above screen capture. )

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.5.1
| PHP version      |  7.2
| Operating system | WindowsServer2016, xampp

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by ArchBlood** [comment]
Is your database collate `utf8mb4_unicode_ci` with character set `utf8mb4`?

**Comment by tomofu74** [comment]
Hi, ArckBlood
I check charset..., oh, it is as that you say.

php_myadmin: post table structure
<img width="530" alt="2020-05-18_110811" src="https://user-images.githubusercontent.com/19162094/82167958-5c88c500-98f8-11ea-919c-ca32fdb8c05e.png">

my.ini: 
<img width="433" alt="2020-05-18_111035" src="https://user-images.githubusercontent.com/19162094/82167992-76c2a300-98f8-11ea-958a-3df288d480b3.png">

If I rewrite my.ini "default-character-set=utf8mb4_unicode_ci" and restart database, does it display correct emoji?
please advice me.

Thank you

**Comment by ArchBlood** [comment]
Using `utf8mb4_unicode_ci` should fix the display issue.

**Comment by tomofu74** [comment]
Thank you, ArchBolood.
I tried it. But,  I could not find anything effective.
Thanks anyway.

**Comment by tomofu74** [comment]
By the way,  I wonder  the emoji icon graphic are different  STREAM content and NOTIFICATION.
That is why? They use different decoder?

**Comment by buddh4** [comment]
The richtext output uses twemoji and the notifications/activities only use the utf-8 emoji character directly. I'll add this to the richtext overview ticket, should not be a big deal to parse the notificatoins etc with twemoji. In HumHub 1.6.3 the missin emoji mapping should be resolved. If its still an issue, please let me know.

**Comment by buddh4** [comment]
https://github.com/humhub/humhub/issues/4215
