### ISSUE TITLE
Error with a database migration to the new content search

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub#7119]
### What steps will reproduce the problem?

Upgrade to HumHub 1.16

### What is the expected result?

No error

### What do you get instead?

Because of the `m240203_112155_search.php` migration, this error occurs:

```
Could not execute content fulltext search migration: SQLSTATE[HY000]: General error: 1221 Incorrect usage of spatial/fulltext/hash index and explicit index order
The SQL being executed was: ALTER TABLE content_fulltext ADD FULLTEXT INDEX ftx (contents ASC, comments ASC, files ASC)
```

Doing it by SQL gives the same error.

### Additional info

Original issue: https://github.com/humhub/wiki/issues/340#issuecomment-2228227851

| Q                | A
| ---------------- | ---
| HumHub version   | 1.16

**Comment by aronbos** [comment]
MySQL - Versie - 8.0.37-0ubuntu0.22.04.3
MySQL - Gegevensbank-sortering - utf8mb4_general_ci
MySQL - Tabel sorteringen - utf8mb4_unicode_ci, utf8mb4_general_ci
MySQL - Tabel-opslagsystemen - InnoDB 

Your database is up-to-date.

No warnings about the database.

**Comment by yurabakhtin** [comment]
@marc-farre I see the log has the old query `ALTER TABLE content_fulltext ADD FULLTEXT INDEX ftx (contents ASC, comments ASC, files ASC)` which was fixed to `ALTER TABLE content_fulltext ADD FULLTEXT INDEX ftx (contents, comments, files)` as we discussed [here](https://github.com/humhub/humhub-internal/issues/230#issuecomment-2089946557).

Probably we should create a new migration to create the fulltext index if it was not created before. Do you agree?

**Comment by marc-farre** [comment]
@yurabakhtin Yes, exactly, I forgot about this issue.
Yes, recreating a new migration by renaming the file and the class name will fix the current issue, and thanks to the `safe` methods, it's not a problem for HumHub instances where this migration already applied.

**Comment by marc-farre** [comment]
@aronbos Thanks for the info. This issue will be fixed in the next version of HumHub, but if you need a quick fix, you can already rename this file and class:
![image](https://github.com/user-attachments/assets/63999d6e-504b-45c4-ac22-594ed6cb2d03)

E.g. to `m240203_112156_search` and then apply the migration in Administration -> Information -> Database.

**Comment by yurabakhtin** [comment]
> @yurabakhtin Yes, exactly, I forgot about this issue. Yes, recreating a new migration by renaming the file and the class name will fix the current issue, and thanks to the `safe` methods, it's not a problem for HumHub instances where this migration already applied.

@marc-farre @luke- Done in the PR https://github.com/humhub/humhub/pull/7120.

**Comment by krseguros** [comment]
Greetings.

Thanks for the follow-up and the intention to help.


![image](https://github.com/user-attachments/assets/0b4bbb76-09d8-433d-985e-57edfb238ab4)

Search index reconstruction underway. The name of the main HumHub database is krseguro_humh575 Your database is up to date.

HumHub  Community Edition Versión: 1.16.1

The issue persists, should I wait for a future update?

**Comment by marc-farre** [comment]
You can add this file on your server: https://github.com/humhub/humhub/pull/7120/files
And then go back to the Database page (the one on your screenshot).

**Comment by krseguros** [comment]
I'm afraid I don't have the necessary knowledge to do this, I have the humhub instance on shared hosting.

Could you tell me the path where to place this file?

**Comment by krseguros** [comment]
Dear, thank you very much for the help, I was able to do it, add the indicated file and that's it. This corrected the problem.

It also solved the search problem I had reported before.

THANK YOU.
![image](https://github.com/user-attachments/assets/7aede157-45da-4640-829a-af3fcc0e1e68)
![image](https://github.com/user-attachments/assets/623a02b4-bcb4-4e3f-a76a-28e01d5331e1)
