### ISSUE TITLE
Directory 0.11.0 After Upgrade: Members / Spaces

### ISSUE THREAD

**Issue by WASasquatch** [humhub/humhub#867]
After upgrading, aside from the Activity Feed which does not load, when I visit "Members" or "Spaces" in the directory, no users but me are listed (searching says they don't exist) and it says there are no spaces.

**Comment by xaro1** [comment]
I remember similar problem corrected by:
yiic search_rebuild
yiic search_optimize

**Comment by WASasquatch** [comment]
Will give it a try in the morning... though YIIC can't even upgrade 0.10.0
or optimize 0.11.0 after manual update. Doesn't see module changes or
anything, even if DB had no modules tables and HumHub is erroring out from
non existing content...

**Comment by andreluis3205** [comment]
I'm having the same problem, how to solve this question?

**Comment by WASasquatch** [comment]
Look at xaro1's answer.

**Comment by ambre-medien** [comment]
I'm having the same problem. I'm sorry but search_rebuild and search_optimize didn't solve it.
